[package]
name = "ophelia"
version = "0.3.4"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia crypto collection"

[dependencies]
anyhow = "1.0"
bytes = "1.1"
ophelia-hasher = "0.2"
rand = "0.7"
