[package]
name = "ophelia-hasher"
version = "0.2.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia hasher trait"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
