[package]
name = "ophelia-quickcheck"
version = "0.2.1"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia quickcheck"

[dependencies]
ophelia-hasher = "0.2"
quickcheck = "1.0"
