[package]
name = "ophelia-derive"
version = "0.1.0"
authors = ["zero.qn <zero.qn@outlook.com>"]
edition = "2018"
license = "MIT"
description = "ophelia derive macros"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
